### ISSUE TITLE
Peer Review#1 - Yun Chu

### ISSUE THREAD

**Issue by chuyun2024** [JianingLi1225/Determinants-of-Wages#1]
Summary
The paper analyzes the factors influencing the wages of US workforce.

Strong positive points:
- the paper is complete and clear
- excellent graph visualization

Critical improvements needed:
- I think having a separate "result" section would be better than putting it as a subsection under "model", since model is just a tool to help you conduct analysis. Result is one of the core section in a paper.
- The readme is partially updated.

Suggestions for improvement:
- maybe consider be more succint and reduce the number of long paragraphs
- the normal qq plot has some points not aligned with the red line, maybe add some justification on that part/future improvement needed so that the model suits better
- add summary statistics in data section
- "Data Result" is not a conclusive/meaningful section name, paraphrase to make it more clear
- Consistent formatting: for each subsection title, consider capitalize the first character of each word, or not capitalize for all
- not sure if this make sense: your sketch is exactly same as the actual plot, but it should be made before the graphs in report, so maybe do a "real" sketch?

Evaluation:
R/Python cited (1/1 pts)
Data cited (1/1 pts)
Class paper (1/1 pts)
LLM documentation (1/1 pts)
Title (2/2 pts)
using both title and subtitle, clearly summarizes the main finding of the paper
Author, date, and repo (2/2 pts)
Abstract (4/4 pts)
Introduction (4/4 pts)
Estimand (1/1 pts)
Data (8/10 pts)
summary statistics is not included
Measurement (4/4 pts)
Model (10/10 pts)
Results (6/10 pts)
No table/graph that illustrates result
Discussion (10/10 pts)
Prose (6/6 pts)
Cross-reference(1/1 pts)
Captions (2/2 pts)
Graphs/tables/etc (4/4 pts)
Surveys, sampling, and observational data appendix (0/10 pts)
this section is not present
Referencing (4/4 pts)
Commits (2/2 pts)
Sketches (1/2 pts)
sketch is made after the graphs are made
Simulation (4/4 pts)
Tests (4//4 pts)
Parquet (1/1 pts)
Reproducible workflow (4/4 pts)
Enhancements (0/4 pts)
Miscellaneous (0/3 pts)
Estimated overall mark:
[98] out of [112].
Any other comments:
Awesome work jianing! :)

**Comment by JianingLi1225** [comment]
Thank you for your comment! You mentioned some details that I hadn't noticed before, such as the case of the title. Regarding the results section, I will also reconsider how to assign paragraphs. Thanks again for your suggestions!
