### ISSUE TITLE
Peer review for Jiangning

### ISSUE THREAD

**Issue by Kr1zzen1** [JianingLi1225/Determinants-of-Wages#4]
_**Summary:**_ 

Key characteristics affecting salaries among the U.S. workforce, such as education, age, gender, race, area, and hours worked, are examined in this study using a multiple linear regression model. According to the findings, education is the most important determinant, with greater education levels translating into noticeably higher salaries. Gender and ethnicity also show substantial differences, with Asian and male workers earning the highest wages. Additionally, the analysis reveals a nonlinear association between salaries and age, with hours worked and geography having minor but noteworthy effects. The research offers evidence to support policies targeted at closing wage inequalities and fostering more equitable economic outcomes by identifying these determinants. 

 _**Strong positive points:**_ 

- The study gains depth by using time-period variables and intersection-specific features, which successfully capture dynamic traffic patterns and fluctuations across important intersections.  

- Transparency is maintained, and readers can easily understand the analysis thanks to the detailed documentation and visualizations of variables like traffic volumes and classifications.  

 
_**Critical improvements needed:**_  

- Citations and references must be improved.  

- The analysis does not take into account external influences, which could have a big impact on traffic patterns. Think about including this in the discussion area.  

- Potential equity concerns or unforeseen implications are not thoroughly examined due to the brief but incomplete description of the effects of tram prioritizing on bikes and pedestrians.  

 
_**Suggestions for improvement:**_ 

- For an in-text reference, include opendatatoronto in the reference.bib.  

- To make clear the dynamic effects of time periods and intersection-specific features, use sophisticated visualizations like interaction plots, time-series graphs, or heatmaps.  

 

_**Evaluation:**_ 

R/Python cited - NOT CITED for the citation! Problem with the paper.pdf's reference section  

Data cited - Included in the publication with a link, but not cited.  

Class paper: 1/1 

Title: 2/2-Informative and highlighting the study's main conclusions.  

Abstract: 2/4; very wordy.  

Introduction: 3/4: It would be better if it were more organized and clear and included information on the research deficit.  

Estimand: 0/1: Described in relation to traffic volume but not specifically found in the data part.  

Data: 8/10: Although there is little discussion of potential biases or exclusions, the data is well-documented.  

Measurement: 3/4 – Gives a description, but might do a better job of explaining how traffic dynamics are translated into quantifiable quantities.  

Model: 10/10: A thorough explanation of the modelling technique is provided.  

Results: 9/10; well-presented, but might use more investigation into variable interactions and residuals.  

Discussion: 8/10: Good discussion of findings, but may use more in-depth analysis of future uses and practical ramifications.  

Prose: 5/6: Technical precision could be somewhat improved, but overall the writing is straightforward and succinct.  

Cross-References: 1/1: Tables and figures are crossed-referenced correctly.  

Caption: 2/2: are thorough and educational.  

Tables & Graphs: 3/4: Although they are useful, the visuals might need more dynamic representations.  

Sampling, surveys, and observational Data: 9/10: Although the approach is explained, sample biases and subtleties of observation are not thoroughly examined.  

Referencing: 1/4: not all references are used.  

Commits: 2/2 – Commits to the repository are frequent and significant.  

Sketched: 0/2:  means that there are no sketches included. (This shouldn't be the case.)  

Simulation: not written (0/4).  

Tests: not written, 0/4  

Parquet: 0/1: No Parquet format was saved.  

Reproducible Workflow: 0/4—no remarks have been written  

Enhancement: 0/4: No extra improvements, like a Shiny app or model card, are offered.  

Miscellaneous: 0/3—still working on the paper, but not meeting the requirements.  

Estimate overall mark: 70/112  

 

_**Additional comments:**_ 

Excellent beginning. There is still a lot to work with. I wish you luck!

**Comment by JianingLi1225** [comment]
Thank you for your comment! But the content seems to be from another student, as mine is not transport related, maybe you can send the review to him so that you can help her better.
