### ISSUE TITLE
peer review by Xiyan Chen

### ISSUE THREAD

**Issue by siaxiyann** [JianingLi1225/Determinants-of-Wages#5]
**Summary**:
This paper analyzed the US wage, using a multiple linear regression model based on polling data from IPUAS US database. It aggregates recent data on education, age, gender, race, region, and hours worked on income. And the paper showing that the role of education, gender, and race as primary drivers of income disparities, while other factors like region and hours worked have smaller effects. 

**Strong Positive Points:**
Strong methods of visualization:
Paper uses effective and various visualizations. I like how you use a table to show give a breif overview of cleaned data. and other figure like Figure 1 used combined pie and bar plot, showing the demographics distribution. Every plots is clear and colorful, aligning with the purpose of analysis.

Modeling and Reproducibility:
The authors utilize polling data from a reputable source ( IPUAS US database), and the dataset appears well-documented. Data cleaning procedures are detailed and clear, enhancing the reproducibility.
The choice of a multiple linear model is a good choice given the need to estimate uncertainties in polling predictions.

Well-written and Structured Paper:
Paper is well-organized, with a good flow from introduction to data analysis, model explanation, and results discussion. Each section is clearly labeled and cross-referenced. The paper is also well-written with concise and professional language.

**Critical Improvements Needed:**
Adding more details in the appendices sections. I like how you show the income distribution on figure 4. But there's no analysis on that figure. Trying to give a more detaied explanation.

Add result section. More analysis needed to be done on the result section. For example, delving into why the model might be the case.  Considering adding details of the results and the discussion on implications of these findings. Talk more here:)

**Suggestions for Improvement:**
In Abstract, I suggest that adding one more sentence about why this matters in a higher level. Considering about the influence on US workforce wage. 

In Model section, it's good to see you explain how each coefficient means. but I think more explanation can be added on why these are included and how modeling reflect aspects discussed in the data section. (You can also do a cross reference here with the figure in data section :) )

Consider adding a catelogue for this paper for reader go to the corresponding section quickly.  Because this is a long paper, and it would be easier to have a catalogue to navigate;)

Evaluation:
R is appropriately cited: 1/1
Data are appropriately cited: 1/1
Class paper: 1/1
LLM usage is documented: 1/1
Title: 2/2
Author, date, and repo: 2/2
Abstract: 3/4
Introduction: 3/4
Estimand: 1/1
Data: 10/10
Measurement: 4/4
Model: 7/10
Results: 0/10
Discussion: 8/10
Prose: 6/6
Cross-referaences: 0.5/1
Captions: 2/2
Graphs/tables/etc: 4/4
Surveys, sampling, and observational data appendix (5/10 pts)
Referencing (4/4 pts)
Commits (2/2 pts)
Sketches (2/2 pts)
Simulation (4/4 pts)
Tests (2/4 pts)
Parquet (1/1 pts)
Reproducible workflow (4/4 pts)
Enhancements (4/4 pts)
Miscellaneous (2/3 pts)
Estimated overall mark: 100.5/126

Other Comments:
Overall, paper is very well-structured and well-written, with effective modeling and strong visualizations. However, some detailed analysis needed to be done such as the explanation of the results and more discussion on the lateral part of the paper needed to be finished up such as the appendices.

**Comment by JianingLi1225** [comment]
Thanks for the advice! I'll refine the results section about the model and add the catalogue, your suggestion helped me a lot!
